.prettierrc
package-lock.json
package.json
src/styles/GlobalStyle.ts
tsconfig.json

✨ globalStyle, prettierrc 설정

---

src/App.tsx
src/components/AppLayout/styles.ts
src/constants/index.ts
src/styles/DefaultTheme.ts
src/styles/GlobalStyle.ts
src/styles/styled.d.ts

:lipstick: DefaultTheme 추가 및 기존의 constants를 theme으로 대체

---

src/components/AppLayout/styles.ts
src/styles/GlobalStyle.ts

:lipstick: AppLayout width 조정 및 GlobalStyle의 font-family 변경

---

src/App.tsx
src/components/AppLayout/AppLayout.tsx
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/components/Profile/ProfileHeader/styles.ts
src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
src/components/Profile/ProfileNavigation/styles.ts
src/components/Profile/VideoItem/VideoItem.tsx
src/components/Profile/VideoItem/styles.ts
src/components/index.ts
src/pages/MyPage.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/ProfilePage/styles.ts
src/pages/index.ts

✨ Profile Page 구현

---

src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
src/components/Profile/ProfileNavigation/styles.ts
src/components/Profile/VideoItem/VideoItem.tsx
src/data/index.ts
src/data/profileData.ts
src/data/videoData.ts

ProfilePage 수정사항 업데이트

---

src/App.tsx
src/pages/UploadPage.tsx
src/pages/VideoUploadPage/VideoUploadPage.tsx
src/pages/VideoUploadPage/styles.ts
src/pages/index.ts

✨ VideoUploadPage UI 및 기본기능 구현

---

package-lock.json
package.json
src/components/Chat/ChatItem/ChatItem.tsx
src/pages/ChatListPage/ChatListPage.tsx
src/utils/api.ts
src/utils/swr.ts

✨ mock server 이용해서 data fetching 로직 추가 (chatList)

---

package-lock.json
package.json
server/db.json
server/routes.json
src/components/Common/AdBanner/AdBanner.tsx
src/components/Common/AdBanner/styles.ts
src/components/Search/SearchBar/SearchBar.tsx
src/components/Search/SearchBar/styles.ts
src/components/index.ts
src/pages/ChatListPage/ChatListPage.tsx
src/pages/ChatListPage/styles.ts
src/pages/SearchPage.tsx
src/pages/SearchPage/SearchPage.tsx
src/pages/SearchPage/styles.ts
src/pages/index.ts
src/styles/GlobalStyle.ts
src/utils/api.ts

✨ Search Page 구현 (검색창, 광고 배너) + json-server 구축

---

src/pages/VideoUploadPage/VideoUploadPage.tsx
src/pages/VideoUploadPage/styles.ts

💄 UploadPage UI 전면 수정

---

package.json
server/index.js
server/routes.json

- 서버 실행 -> `npm start`
- 앱 실행 -> `npm run dev`

🚀 Heroku 환경에 맞춰 json-server 수정 후 배포

---

src/App.tsx
src/components/Admin/AdminContents/AdminContents.tsx
src/components/Admin/AdminContents/styles.ts
src/components/Admin/AdminNav/AdminNav.tsx
src/components/Admin/AdminNav/styles.ts
src/components/Admin/AdminUser/AdminUser.tsx
src/components/index.ts
src/pages/AdminPage/AdminPage.tsx
src/pages/AdminPage/styles.ts
src/pages/index.ts

라우팅 처리까지 완료해서 주영님은 components / Admin / AdminUser안에서 작업하시면 됩니다!
Nav가 겹쳐서 conflict 발생할까봐 먼저 올려드립니당!! 혹시 수정사항있으면 알려주세용 💕

✨ AdminPage 라우팅 설정 및 AdminNav 추가

---

package-lock.json
package.json
src/components/Common/VideoItem/styles.ts
src/components/Search/HistoryList/HistoryList.tsx
src/components/Search/HistoryList/styles.ts
src/components/Search/HorizonVideoList/HorizonVideoList.tsx
src/components/Search/HorizonVideoList/styles.ts
src/components/Search/SearchBar/SearchBar.tsx
src/components/Search/SearchBar/styles.ts
src/components/index.ts
src/pages/SearchPage/SearchPage.tsx
src/pages/SearchPage/styles.ts
src/utils/api.ts

✨ Search Page 구현 (최근검색어, 추천 및 인기영상)

---

src/App.tsx
src/components/AppLayout/styles.ts
src/components/Common/PageHeader/styles.ts
src/components/Common/VideoList/VideoList.tsx
src/components/Common/VideoList/styles.ts
src/components/Profile/ProfileNavigation/ProfileNavigation.tsx
src/components/Profile/ProfileNavigation/styles.ts
src/components/Search/HistoryList/HistoryList.tsx
src/components/Search/HistoryList/styles.ts
src/components/Search/SearchBar/SearchBar.tsx
src/components/index.ts
src/pages/SearchPage/SearchPage.tsx
src/pages/SearchPage/types.d.ts
src/pages/SearchResultPage/SearchResultPage.tsx
src/pages/SearchResultPage/styles.ts
src/pages/index.ts

✨ Search Result Page 구현

---

src/components/Common/LoginButton/LoginButton.tsx
src/components/Common/LoginButton/styles.ts
src/components/Common/LoginModal/LoginModal.tsx
src/components/Common/LoginModal/styles.ts
src/components/Search/HorizonVideoList/HorizonVideoList.tsx
src/components/Search/HorizonVideoList/styles.ts
src/components/index.ts
src/pages/ChatListPage/ChatListPage.tsx
src/pages/ChatListPage/styles.ts

사용 할 때 props로 padding 값 전달해주세요
사용할 때 Modal 추가하는 위치의 부모 요소에 `position:relative` 추가해주세요

💄 로그인 요청을 위한 LoginButton & LoginModal UI 추가

---

src/App.tsx
src/components/Login/KakaoLogin/Auth.tsx
src/components/Login/KakaoLogin/KakaoLogin.tsx
src/components/Login/KakaoLogin/styles.ts
src/components/index.ts
src/pages/LoginPage/LoginPage.tsx
src/pages/index.ts

:sparkles: 카카오 로그인 및 로그인 페이지 추가 - 테스팅용

---

src/App.tsx
src/components/Admin/AdminNav/AdminNav.tsx
src/components/Admin/UserDashBoard/UserDashBoard.tsx
src/components/Admin/UserDataTable/UserDataTable.tsx
src/components/Admin/UserDataTable/columns.ts
src/components/Admin/UserDataTable/styles.ts
src/components/Admin/VideoDataTable/VideoDataTable.tsx
src/components/Admin/VideoDataTable/columns.ts
src/components/Admin/VideoDataTable/styles.ts
src/components/Layouts/AdminLayout/AdminLayout.tsx
src/components/index.ts
src/pages/AdminDashBoard/AdminDashBoard.tsx
src/pages/AdminDashBoard/styles.ts
src/pages/index.ts

✨ Admin User Dashboard 페이지 구현

---

server/db.json
server/index.js
src/App.tsx
src/components/Common/PageHeader/styles.ts
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/components/Profile/ProfileHeader/styles.ts
src/data/profileData.ts
src/data/types.d.ts
src/pages/FollowPage/FollowPage.tsx
src/pages/FollowPage/styles.ts
src/pages/index.ts
src/utils/api.ts

✨ Follow Page 구현 (팔로잉 & 팔로워)

---

src/App.tsx
src/pages/PlayPage/PlayPage.tsx
src/pages/PlayPage/styles.ts
src/pages/index.ts

:sparkles: VideoPlay 페이지 추가

---

src/components/Common/Modal/LoginModal.tsx
src/components/Login/KakaoLogin/styles.ts
src/pages/LoginPage/LoginPage.tsx
src/pages/LoginPage/styles.ts
src/utils/api.ts

💄 카카오 로그인 페이지 UI 완성

---

src/components/Common/Modal/DeleteModal.tsx
src/components/Common/Modal/LoginModal.tsx
src/components/Common/Modal/MessageModal.tsx
src/components/Common/Modal/styles.ts
src/components/index.ts
src/pages/VideoUploadPage/VideoUploadPage.tsx
src/utils/api.ts

✨ 영상 업로드 로직 구현 / 메세지 모달창 추가

---

src/components/Common/Modal/DeleteModal.tsx
src/components/Main/ContentsWrap/ContentsWrap.tsx
src/components/Main/DescriptionBox/DescriptionBox.tsx
src/data/types.d.ts
src/pages/MainPage/MainPage.tsx
src/utils/api.ts

- 테스팅을 위해서 /video/:videoId (주영님이 등록한 영상 id) 입력하시고 삭제해보시면 될겁니다! 
- 테스팅을 위해서 type을 delete로 임시로 변경한 상태입니다!

✨ 영상 삭제 구현, 영상 재생 api 교체

---

src/components/Main/ContentsWrap/ContentsWrap.tsx
src/components/Main/NavMenu/PlayerMenu.tsx
src/components/Main/NavMenu/styles.ts
src/pages/MainPage/MainPage.tsx
src/utils/api.ts
src/utils/swr.ts

✨ 영상재생 페이지에 좋아요 등록 구현

---

package-lock.json
package.json
src/App.tsx
src/components/Common/Modal/LoginModal.tsx
src/components/Layouts/AppLayout/AppLayout.tsx
src/components/Login/KakaoLogin/KakaoRedirectHandler.tsx
src/components/Main/MainHeader/MainHeader.tsx
src/components/Main/MainHeader/styles.ts
src/components/Main/NavMenu/IconFeature/ChatButton.tsx
src/components/Main/NavMenu/IconFeature/LikeButton.tsx
src/components/Main/NavMenu/IconFeature/ProfileFollow.tsx
src/components/Main/NavMenu/UserVideoNav/UserVideoNav.tsx
src/components/Route/PrivateRoute.tsx
src/components/index.ts
src/index.tsx
src/pages/ChatListPage/ChatListPage.tsx
src/pages/NotificationPage/NotificationPage.tsx
src/pages/index.ts
src/recoil/atom.ts
src/utils/isLogin.ts

♻️ Private Route 설정, 로그인 여부에 따라 LoginModal 보여주기 추가

---

src/components/Main/NavMenu/IconFeature/LikeButton.tsx
src/components/Main/NavMenu/IconFeature/ProfileFollow.tsx
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/pages/FollowPage/FollowPage.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/utils/api.ts

♻️ mainPage 좋아요, 팔로우 기능 수정 및 추가 & profilePage 팔로워, 팔로잉 부분 수정
